# -*- coding: utf-8 -*-
"""kadai_013.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qb2KO-QtXlUkW-XykDDuE3FQCw4vArjb
"""

def product_price1(net_price):
  return net_price + net_price * 0.1

def product_price2(net_price, tax):
  return net_price + net_price * tax * 0.01