# -*- coding: utf-8 -*-
"""kadai_008.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_K1q5ZSoYQF7rr38vkeL3j8_wi7MRU5
"""

var = int(input())
if var % 3 == 0 and var % 5 == 0:
  print("FizzBuzz")
elif var % 3 == 0:
  print("Fizz")
elif var % 5 == 0:
  print("Buzz")
else:
  print(var)