# -*- coding: utf-8 -*-
"""kadai_013.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qb2KO-QtXlUkW-XykDDuE3FQCw4vArjb
"""

def product_price(gross_price, tax):
  return gross_price + gross_price * tax * 0.01

product_price(100,10)