# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uVzd6of0PnKZlddATGOe2PZY6RpXs4s
"""

top_edge = 10
bottom_edge = 20
height = 5

area_of_trapezoid = ((top_edge + bottom_edge) * height) / 2
print(f"台形の面積は{area_of_trapezoid}cm^2です。")