# -*- coding: utf-8 -*-
"""kadai_011.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tyMCF7XM7Czua4FdkRiaA9aIUm31zy-g
"""

array = ["水","金","地","火","木","土","天","海","冥"]

for value in array:
  print(value)

number = len(array)
i = 0
while i < number:
  print(array[i])
  i = i + 1